### ISSUE TITLE
Specify what flavour of markdown this parses in package description and homepage

### ISSUE THREAD

**Issue by shonfeder** [gildor478/ocaml-markdown#6]
It seems that this expects some unusual variant of markdown, in which (at least) headings are indicated by preceding `!` instead of preceding `#`. Are there other unusual variations? I'm not sure, but I think users shouldn't have to inspect the source to code to find out.

I didn't discover this until I'd spent more than hour plugging this into my system, because it's not documented anywhere that I could see. Since this package has claimed the name `markdown` in the opam registry, (which is itself quite misleading if it's actually an unusual variant of markdown) I think this kind of documentation on both the homepage and the package description is important.

**Comment by gildor478** [comment]
I am actually not sure what flavor is used here. I have extracted this library from [ocsiblog], 9 years ago.

AFAIR, the `!` was used to avoid ambiguity when parsing. I quickly had a look at the various variants of Markdown but didn't find anything matching. I can document the unusual use of `!`, but I don't think I can name a variant that is using the same construct.

Let me know if you know such a variant.

[ocsiblog]: https://github.com/mfp/ocsiblog

**Comment by shonfeder** [comment]
Thank! My searches haven't turned up any known flavor that uses this syntax either. This make suspect it is an idiosyncratic variant. Something like the following in the description and readme would probably suffice:

> This is a pure OCaml parser for a **non-standard dialect** of Markdown. 
> See the docs for notes on how this flavor differs from common Markdown syntax.

**Comment by shonfeder** [comment]
Thank you!
